In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import train_test_split

# https://www.kaggle.com/brandao/diabetes/home

diabetes = pd.read_csv("/Users/alisalem/Downloads/diabetes/diabetic_data.csv",na_values="?")

/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
diabetes = pd.DataFrame(diabetes) 
diabetes.rename(columns={'glyburide-metformin': 'glyburide_metformin'}, inplace=True)
diabetes.rename(columns={'glipizide-metformin': 'glipizide_metformin'}, inplace=True)
diabetes.rename(columns={'glimepiride-pioglitazone': 'glimepiride_pioglitazone'}, inplace=True)
diabetes.rename(columns={'metformin-rosiglitazone': 'metformin_rosiglitazone'}, inplace=True)
diabetes.rename(columns={'metformin-pioglitazone': 'metformin_pioglitazone'}, inplace=True)

diabetes

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),NaN,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),NaN,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),NaN,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),NaN,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),NaN,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,...,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),NaN,2,1,4,7,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),NaN,1,3,7,7,...,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),NaN,1,6,7,10,...,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),NaN,3,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),NaN,1,3,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),NaN,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),NaN,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),NaN,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,NaN,Male,[70-80),NaN,3,6,2,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,NaN,Female,[50-60),NaN,2,1,4,2,...,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,NaN,Male,[60-70),NaN,2,1,4,2,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),NaN,2,1,4,2,...,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),NaN,2,6,1,11,...,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),NaN,3,1,2,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),NaN,1,3,7,6,...,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),NaN,1,1,1,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),NaN,2,1,2,10,...,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),NaN,1,2,7,5,...,No,No,No,No,No,No,No,Ch,Yes,>30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101736,443739152,90751788,Caucasian,Female,[60-70),NaN,1,3,7,8,...,No,Steady,No,No,No,No,No,No,Yes,>30
101737,443775086,125764160,Caucasian,Female,[40-50),NaN,3,1,1,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101738,443775482,95780439,Caucasian,Male,[70-80),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
101739,443775740,30656952,AfricanAmerican,Male,[70-80),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,No,Yes,NO
101740,443778398,134647673,Caucasian,Male,[40-50),NaN,3,1,1,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101741,443787128,58160520,AfricanAmerican,Male,[90-100),NaN,1,3,7,4,...,No,No,No,No,No,No,No,No,No,NO
101742,443787512,52419276,Caucasian,Male,[70-80),NaN,2,6,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101743,443793668,47293812,Caucasian,Male,[80-90),NaN,1,13,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101744,443793992,43686936,Caucasian,Female,[80-90),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,No,NO
101745,443797076,183766055,Caucasian,Male,[50-60),NaN,2,1,1,3,...,No,No,No,No,No,No,No,Ch,Yes,NO
101746,443797298,89955270,Caucasian,Male,[70-80),NaN,1,1,7,4,...,No,No,No,No,No,No,No,No,Yes,<30
101747,443804570,33230016,Caucasian,Female,[70-80),NaN,1,22,7,8,...,No,Steady,No,No,No,No,No,No,Yes,>30
101748,443811536,189481478,Caucasian,Female,[40-50),NaN,1,4,7,14,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101749,443816024,106392411,Caucasian,Female,[70-80),NaN,3,6,1,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101750,443824292,138784172,Caucasian,Female,[80-90),NaN,3,1,1,3,...,No,Down,No,No,No,No,No,Ch,Yes,<30
101751,443835140,175326800,Caucasian,Male,[70-80),NaN,3,6,1,13,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101752,443835512,139605341,Other,Female,[40-50),NaN,3,1,1,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
101753,443841992,184875899,Other,Male,[40-50),NaN,1,1,7,13,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101754,443842016,183087545,Caucasian,Female,[70-80),NaN,1,1,7,9,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
101755,443842022,188574944,Other,Female,[40-50),NaN,1,1,7,14,...,No,Up,No,No,No,No,No,Ch,Yes,>30
101756,443842070,140199494,Other,Female,[60-70),NaN,1,1,7,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
101757,443842136,181593374,Caucasian,Female,[70-80),NaN,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101758,443842340,120975314,Caucasian,Female,[80-90),NaN,1,1,7,5,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101759,443842778,86472243,Caucasian,Male,[80-90),NaN,1,1,7,1,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101760,443847176,50375628,AfricanAmerican,Female,[60-70),NaN,1,1,7,6,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101761,443847548,100162476,AfricanAmerican,Male,[70-80),NaN,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),NaN,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),NaN,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),NaN,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),NaN,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [3]:
del diabetes["weight"]
del diabetes["medical_specialty"]
del diabetes["payer_code"]

diabetes.drop(['encounter_id','patient_nbr', 'admission_type_id', 'discharge_disposition_id','admission_source_id'], axis = 1, inplace = True)

In [4]:
diabetes.race.mode()

0    Caucasian
dtype: object

In [5]:
diabetes.race = diabetes.race.fillna(diabetes.race.mode()[0])

In [6]:
diabetes.isnull().sum()

race                           0
gender                         0
age                            0
time_in_hospital               0
num_lab_procedures             0
num_procedures                 0
num_medications                0
number_outpatient              0
number_emergency               0
number_inpatient               0
diag_1                        21
diag_2                       358
diag_3                      1423
number_diagnoses               0
max_glu_serum                  0
A1Cresult                      0
metformin                      0
repaglinide                    0
nateglinide                    0
chlorpropamide                 0
glimepiride                    0
acetohexamide                  0
glipizide                      0
glyburide                      0
tolbutamide                    0
pioglitazone                   0
rosiglitazone                  0
acarbose                       0
miglitol                       0
troglitazone                   0
tolazamide                     0
examide                        0
citoglipton                    0
insulin                        0
glyburide_metformin            0
glipizide_metformin            0
glimepiride_pioglitazone       0
metformin_rosiglitazone        0
metformin_pioglitazone         0
change                         0
diabetesMed                    0
readmitted                     0
dtype: int64

In [7]:
diabetes.diag_1 = diabetes['diag_1'].astype(str)
for i in range(diabetes.shape[0]):
    if 'V' in diabetes.diag_1[i]:
        diabetes.diag_1[i] = diabetes.diag_1[i].replace("V","")
    if "E" in diabetes.diag_1[i]:
        diabetes.diag_1[i] = diabetes.diag_1[i].replace("E","")
    if 'nan' in diabetes.diag_1[i]:
        diabetes.diag_1[i] = diabetes.diag_1[i].replace("nan","")
diabetes.diag_1 = pd.to_numeric(diabetes.diag_1)
diabetes.diag_1 = diabetes.diag_1.fillna(diabetes.diag_1.mode()[0])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
diabetes.diag_2 = diabetes['diag_2'].astype(str)
for i in range(diabetes.shape[0]):
    if "V" in diabetes.diag_2[i]:
        diabetes.diag_2[i] = diabetes.diag_2[i].replace("V","")
    if "E" in diabetes.diag_2[i]:
        diabetes.diag_2[i] = diabetes.diag_2[i].replace("E","")
    if 'nan' in diabetes.diag_2[i]:
        diabetes.diag_2[i] = diabetes.diag_2[i].replace("nan","")
diabetes.diag_2 = pd.to_numeric(diabetes.diag_2)
diabetes.diag_2 = diabetes.diag_2.fillna(diabetes.diag_2.mode()[0])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [9]:
diabetes.diag_3 = diabetes['diag_3'].astype(str)
for i in range(diabetes.shape[0]):
    if "V" in diabetes.diag_3[i]:
        diabetes.diag_3[i] = diabetes.diag_3[i].replace("V","")
    if "E" in diabetes.diag_3[i]:
        diabetes.diag_3[i] = diabetes.diag_3[i].replace("E","")
    if 'nan' in diabetes.diag_3[i]:
        diabetes.diag_3[i] = diabetes.diag_3[i].replace("nan","")
diabetes.diag_3 = pd.to_numeric(diabetes.diag_3)
diabetes.diag_3 = diabetes.diag_3.fillna(diabetes.diag_3.mode()[0])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [10]:
diabetes['diag_1'] = diabetes['diag_1'].astype(int)
diabetes['diag_2'] = diabetes['diag_2'].astype(int)
diabetes['diag_3'] = diabetes['diag_3'].astype(int)

In [11]:
diabetes.dtypes

race                        object
gender                      object
age                         object
time_in_hospital             int64
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                       int64
diag_2                       int64
diag_3                       int64
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide_metformin         object
glipizide_metformin         object
glimepiride_pioglitazone    object
metformin_rosiglitazone     object
metformin_pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [12]:
diabetes.race = diabetes.race.astype('category')
diabetes.gender = diabetes.gender.astype('category')
diabetes.max_glu_serum = diabetes.max_glu_serum.astype('category')
diabetes.A1Cresult = diabetes.A1Cresult.astype('category')
diabetes.metformin = diabetes.metformin.astype('category')
diabetes.repaglinide = diabetes.repaglinide.astype('category')
diabetes.nateglinide = diabetes.nateglinide.astype('category')
diabetes.chlorpropamide = diabetes.chlorpropamide.astype('category')
diabetes.glimepiride = diabetes.glimepiride.astype('category')
diabetes.acetohexamide = diabetes.acetohexamide.astype('category')
diabetes.glipizide = diabetes.glipizide.astype('category')
diabetes.glyburide = diabetes.glyburide.astype('category')
diabetes.tolbutamide = diabetes.tolbutamide.astype('category')
diabetes.pioglitazone = diabetes.pioglitazone.astype('category')
diabetes.rosiglitazone = diabetes.rosiglitazone.astype('category')
diabetes.acarbose = diabetes.acarbose.astype('category')
diabetes.miglitol = diabetes.miglitol.astype('category')
diabetes.troglitazone = diabetes.troglitazone.astype('category')
diabetes.tolazamide = diabetes.tolazamide.astype('category')
diabetes.examide = diabetes.examide.astype('category')
diabetes.citoglipton = diabetes.citoglipton.astype('category')
diabetes.insulin = diabetes.insulin.astype('category')
diabetes.glyburide_metformin = diabetes.glyburide_metformin.astype('category')
diabetes.glipizide_metformin = diabetes.glipizide_metformin.astype('category')
diabetes.glimepiride_pioglitazone  = diabetes.glimepiride_pioglitazone.astype('category')
diabetes.metformin_rosiglitazone = diabetes.metformin_rosiglitazone.astype('category')
diabetes.metformin_pioglitazone = diabetes.metformin_pioglitazone.astype('category')
diabetes.change = diabetes.change.astype('category')
diabetes.diabetesMed = diabetes.diabetesMed.astype('category')
diabetes.readmitted = diabetes.readmitted.astype('category')


le=LabelEncoder()
le.fit(diabetes.race)
diabetes.race = le.transform(diabetes.race)

le.fit(diabetes.gender)
diabetes.gender = le.transform(diabetes.gender)

le.fit(diabetes.max_glu_serum)
diabetes.max_glu_serum = le.transform(diabetes.max_glu_serum)

le.fit(diabetes.A1Cresult)
diabetes.A1Cresult = le.transform(diabetes.A1Cresult)

le.fit(diabetes.metformin)
diabetes.metformin = le.transform(diabetes.metformin)

le.fit(diabetes.repaglinide)
diabetes.repaglinide = le.transform(diabetes.repaglinide)

le.fit(diabetes.nateglinide)
diabetes.nateglinide = le.transform(diabetes.nateglinide)

le.fit(diabetes.chlorpropamide)
diabetes.chlorpropamide = le.transform(diabetes.chlorpropamide)

le.fit(diabetes.glimepiride)
diabetes.glimepiride = le.transform(diabetes.glimepiride)

le.fit(diabetes.acetohexamide)
diabetes.acetohexamide = le.transform(diabetes.acetohexamide)

le.fit(diabetes.glipizide)
diabetes.glipizide = le.transform(diabetes.glipizide)

le.fit(diabetes.glyburide)
diabetes.glyburide = le.transform(diabetes.glyburide)

le.fit(diabetes.tolbutamide)
diabetes.tolbutamide = le.transform(diabetes.tolbutamide)

le.fit(diabetes.pioglitazone)
diabetes.pioglitazone = le.transform(diabetes.pioglitazone)

le.fit(diabetes.rosiglitazone)
diabetes.rosiglitazone = le.transform(diabetes.rosiglitazone)

le.fit(diabetes.acarbose)
diabetes.acarbose = le.transform(diabetes.acarbose)

le.fit(diabetes.miglitol)
diabetes.miglitol = le.transform(diabetes.miglitol)

le.fit(diabetes.troglitazone)
diabetes.troglitazone = le.transform(diabetes.troglitazone)

le.fit(diabetes.tolazamide)
diabetes.tolazamide = le.transform(diabetes.tolazamide)

le.fit(diabetes.examide)
diabetes.examide = le.transform(diabetes.examide)

le.fit(diabetes.citoglipton)
diabetes.citoglipton = le.transform(diabetes.citoglipton)

le.fit(diabetes.insulin)
diabetes.insulin = le.transform(diabetes.insulin)

le.fit(diabetes.glyburide_metformin)
diabetes.glyburide_metformin = le.transform(diabetes.glyburide_metformin)

le.fit(diabetes.glipizide_metformin)
diabetes.glipizide_metformin = le.transform(diabetes.glipizide_metformin)

le.fit(diabetes.glimepiride_pioglitazone )
diabetes.glimepiride_pioglitazone  = le.transform(diabetes.glimepiride_pioglitazone )

le.fit(diabetes.metformin_rosiglitazone)
diabetes.metformin_rosiglitazone = le.transform(diabetes.metformin_rosiglitazone)

le.fit(diabetes.metformin_pioglitazone )
diabetes.metformin_pioglitazone  = le.transform(diabetes.metformin_pioglitazone )

le.fit(diabetes.change)
diabetes.change = le.transform(diabetes.change)

le.fit(diabetes.diabetesMed)
diabetes.diabetesMed = le.transform(diabetes.diabetesMed)


diabetes.dtypes

race                           int64
gender                         int64
age                           object
time_in_hospital               int64
num_lab_procedures             int64
num_procedures                 int64
num_medications                int64
number_outpatient              int64
number_emergency               int64
number_inpatient               int64
diag_1                         int64
diag_2                         int64
diag_3                         int64
number_diagnoses               int64
max_glu_serum                  int64
A1Cresult                      int64
metformin                      int64
repaglinide                    int64
nateglinide                    int64
chlorpropamide                 int64
glimepiride                    int64
acetohexamide                  int64
glipizide                      int64
glyburide                      int64
tolbutamide                    int64
pioglitazone                   int64
rosiglitazone                  int64
acarbose                       int64
miglitol                       int64
troglitazone                   int64
tolazamide                     int64
examide                        int64
citoglipton                    int64
insulin                        int64
glyburide_metformin            int64
glipizide_metformin            int64
glimepiride_pioglitazone       int64
metformin_rosiglitazone        int64
metformin_pioglitazone         int64
change                         int64
diabetesMed                    int64
readmitted                  category
dtype: object

In [13]:
diabetes.head(5)

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,citoglipton,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,diabetesMed,readmitted
0,2,0,[0-10),1,41,0,1,0,0,0,...,0,1,1,0,0,0,0,1,0,NO
1,2,0,[10-20),3,59,0,18,0,0,0,...,0,3,1,0,0,0,0,0,1,>30
2,0,0,[20-30),2,11,5,13,2,0,1,...,0,1,1,0,0,0,0,1,1,NO
3,2,1,[30-40),2,44,1,16,0,0,0,...,0,3,1,0,0,0,0,0,1,NO
4,2,1,[40-50),1,51,0,8,0,0,0,...,0,2,1,0,0,0,0,0,1,NO

In [14]:
diabetes['age'] = diabetes['age'].str[:-1].str.split('-',expand=True)[1]
diabetes['age'] = diabetes['age'].astype(int)

In [15]:
diabetes.head(20)

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,citoglipton,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,diabetesMed,readmitted
0,2,0,10,1,41,0,1,0,0,0,...,0,1,1,0,0,0,0,1,0,NO
1,2,0,20,3,59,0,18,0,0,0,...,0,3,1,0,0,0,0,0,1,>30
2,0,0,30,2,11,5,13,2,0,1,...,0,1,1,0,0,0,0,1,1,NO
3,2,1,40,2,44,1,16,0,0,0,...,0,3,1,0,0,0,0,0,1,NO
4,2,1,50,1,51,0,8,0,0,0,...,0,2,1,0,0,0,0,0,1,NO
5,2,1,60,3,31,6,16,0,0,0,...,0,2,1,0,0,0,0,1,1,>30
6,2,1,70,4,70,1,21,0,0,0,...,0,2,1,0,0,0,0,0,1,NO
7,2,1,80,5,73,0,12,0,0,0,...,0,1,1,0,0,0,0,1,1,>30
8,2,0,90,13,68,2,28,0,0,0,...,0,2,1,0,0,0,0,0,1,NO
9,2,0,100,12,33,3,18,0,0,0,...,0,2,1,0,0,0,0,0,1,NO
10,0,0,50,9,47,2,17,0,0,0,...,0,2,1,0,0,0,0,1,1,>30
11,0,1,70,7,62,0,11,0,0,0,...,0,2,1,0,0,0,0,0,1,<30
12,2,0,50,7,60,0,15,0,1,0,...,0,0,1,0,0,0,0,0,1,<30
13,2,1,90,10,55,1,31,0,0,0,...,0,2,1,0,0,0,0,1,1,NO
14,0,0,70,1,49,5,2,0,0,0,...,0,2,1,0,0,0,0,1,1,>30
15,0,1,70,12,75,5,13,0,0,0,...,0,3,1,0,0,0,0,0,1,NO
16,0,1,60,4,45,4,17,0,0,0,...,0,2,1,0,0,0,0,0,1,<30
17,2,0,60,3,29,0,11,0,0,0,...,0,1,1,0,0,0,0,1,1,NO
18,0,1,80,5,35,5,23,0,0,0,...,0,2,1,0,0,0,0,1,1,>30
19,2,1,80,6,42,2,23,0,0,0,...,0,2,1,0,0,0,0,0,1,NO

In [16]:
diabetes['readmitted'].value_counts()

NO     54864
>30    35545
<30    11357
Name: readmitted, dtype: int64

In [17]:
diabetes['readmitted'] = np.where(diabetes['readmitted']!='NO',1,0)
#diabetes['readmitted'] = diabetes['readmitted'].replace('>30', 0)
#diabetes['readmitted'] = diabetes['readmitted'].replace('<30', 1)
#diabetes['readmitted'] = diabetes['readmitted'].replace('NO', 0)
diabetes.head(5)

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,citoglipton,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,diabetesMed,readmitted
0,2,0,10,1,41,0,1,0,0,0,...,0,1,1,0,0,0,0,1,0,0
1,2,0,20,3,59,0,18,0,0,0,...,0,3,1,0,0,0,0,0,1,1
2,0,0,30,2,11,5,13,2,0,1,...,0,1,1,0,0,0,0,1,1,0
3,2,1,40,2,44,1,16,0,0,0,...,0,3,1,0,0,0,0,0,1,0
4,2,1,50,1,51,0,8,0,0,0,...,0,2,1,0,0,0,0,0,1,0

In [18]:
X = diabetes.drop('readmitted',axis=1)
Y = diabetes['readmitted']

In [19]:
diabetes.dtypes

race                        int64
gender                      int64
age                         int64
time_in_hospital            int64
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                      int64
diag_2                      int64
diag_3                      int64
number_diagnoses            int64
max_glu_serum               int64
A1Cresult                   int64
metformin                   int64
repaglinide                 int64
nateglinide                 int64
chlorpropamide              int64
glimepiride                 int64
acetohexamide               int64
glipizide                   int64
glyburide                   int64
tolbutamide                 int64
pioglitazone                int64
rosiglitazone               int64
acarbose                    int64
miglitol                    int64
troglitazone                int64
tolazamide                  int64
examide                     int64
citoglipton                 int64
insulin                     int64
glyburide_metformin         int64
glipizide_metformin         int64
glimepiride_pioglitazone    int64
metformin_rosiglitazone     int64
metformin_pioglitazone      int64
change                      int64
diabetesMed                 int64
readmitted                  int64
dtype: object

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state =0)
logit = LogisticRegression(random_state=0)
logit.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
y_pred = logit.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.618207723297632